### PR TITLE
Delete everything at HEAD.  This repo is no longer active.

### PR DESCRIPTION
**Pull request by sbc100**
The wasm waterfall recently switch to wasi-sysroot.  So I assume this repo is now a dead end.

I've left a README in place to redirect people.

### CODE REVIEW

**Comment by jfbastien** [comment]
I don't think we need to delete everything. Just updating the readme is sufficient.

**Comment by sbc100** [comment]
I kind of like deleting everything because it means as soon as you pull from the repo you can help but notice.

But will do it your way if you prefer.

**Comment by jfbastien** [comment]
I see the repo as historical, so just a thing at the top of the readme should be sufficient IMO. If someone pulls a random repo and gets confused... they'll read the readme :)

**Comment by sbc100** [comment]
Yes, repo is historical.. and the history is all still there in either case.    But I'll go with your choice.

**Pull request closed without merging**
